// mobile/styles/MainKierowcaStyles.ts
import { StyleSheet } from 'react-native';

export const MainKierowcaStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f7f6',
  },
  header: {
    backgroundColor: '#0a1d56',
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomWidth: 4,
    borderBottomColor: '#FFD700',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoImage: {
    width: 180,
    height: 50,
    backgroundColor: '#fff',
  },
  menuButton: {
    padding: 5,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    zIndex: 1000,
  },
  sideMenu: {
    position: 'absolute',
    top: 0,
    right: -280,
    width: 280,
    height: '100%',
    backgroundColor: '#fff',
    zIndex: 1001,
    paddingTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  sideMenuOpen: {
    right: 0,
  },
  closeMenuBtn: {
    alignSelf: 'flex-end',
    padding: 15,
  },
  menuHeader: {
    backgroundColor: '#f8f9fa',
    padding: 20,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  menuHeaderText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#333',
  },
  currentVehicle: {
    backgroundColor: '#f0f4f8',
    margin: 15,
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  vehicleLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
  },
  vehicleNameText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#002255',
  },
  vehiclePlate: {
    fontSize: 13,
    color: '#333',
    marginBottom: 10,
  },
  releaseBtn: {
    backgroundColor: '#dc3545',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 4,
    width: '100%',
  },
  releaseBtnText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
    textAlign: 'center',
  },
  menuItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  menuItemActive: {
    backgroundColor: '#f0f4f8',
  },
  menuItemText: {
    fontSize: 15,
    color: '#444',
  },
  menuItemTextActive: {
    color: '#002255',
    fontWeight: 'bold',
  },
  menuBottom: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  logoutText: {
    color: '#e74c3c',
    fontWeight: 'bold',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectionContainer: {
    flex: 1,
    padding: 20,
  },
  selectionCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  selectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#002255',
    textAlign: 'center',
    marginBottom: 10,
  },
  selectionSubtitle: {
    textAlign: 'center',
    color: '#666',
    marginBottom: 20,
  },
  noVehicles: {
    textAlign: 'center',
    color: '#e74c3c',
    padding: 20,
  },
  vehicleItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    padding: 15,
    marginBottom: 10,
  },
  vehicleInfo: {
    flex: 1,
  },
  vehicleName: {
    fontWeight: 'bold',
    color: '#002255',
    fontSize: 16,
  },
  vehicleDetail: {
    color: '#555',
    fontSize: 14,
  },
  selectBtn: {
    backgroundColor: '#28a745',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
  },
  selectBtnText: {
    color: 'white',
    fontWeight: 'bold',
  },
  mainContent: {
    flex: 1,
    padding: 16,
  },
  tasksLayout: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  sidebar: {
    width: '100%',
    marginBottom: 16,
  },
  taskCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  panelTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#002255',
    textAlign: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#f0f4f8',
  },
  tasksContainer: {
    gap: 12,
  },
  taskItem: {
    backgroundColor: '#f8f9fa',
    borderWidth: 1,
    borderColor: '#dde1e5',
    borderRadius: 8,
    padding: 12,
  },
  taskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  taskTime: {
    color: '#e67e22',
    fontWeight: 'bold',
    fontSize: 13,
  },
  taskDistance: {
    color: '#666',
    fontSize: 13,
  },
  taskRoute: {
    gap: 4,
    marginBottom: 8,
  },
  bold: {
    fontWeight: 'bold',
    color: '#002255',
  },
  taskActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  rejectBtn: {
    flex: 1,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#e74c3c',
    borderRadius: 6,
    paddingVertical: 8,
    alignItems: 'center',
  },
  rejectBtnText: {
    color: '#e74c3c',
    fontWeight: 'bold',
  },
  acceptBtn: {
    flex: 2,
    backgroundColor: '#2ecc71',
    borderRadius: 6,
    paddingVertical: 8,
    alignItems: 'center',
  },
  acceptBtnText: {
    color: 'white',
    fontWeight: 'bold',
  },
  mapArea: {
    width: '100%',
  },
  mapCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    height: 300,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#dde1e5',
    borderStyle: 'dashed',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  mapPlaceholder: {
    fontWeight: '800',
    fontSize: 18,
    color: '#a0aab5',
  },
  historyArea: {
    flex: 1,
  },
});